name: Prettier

on:
  workflow_call:
    secrets:
      ECOSPARK_APP_ID:
        required: true
      ECOSPARK_APP_PRIVATE_KEY:
        required: true

concurrency:
  group: ${{ github.repository_owner_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    if: github.repository_owner == 'sanity-io'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install
      - run: pnpm format
      - run: git restore .github/workflows pnpm-lock.yaml
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          body: I ran `pnpm format` üßë‚Äçüíª
          branch: actions/format-${{ github.ref_name }}
          commit-message: "chore(format): ü§ñ ‚ú®"
          delete-branch: true
          labels: ü§ñ bot
          sign-commits: true
          title: "chore(format): ü§ñ ‚ú®"
          token: ${{ steps.app-token.outputs.token }}
